### ISSUE TITLE
请问如何配置自己放的cookie/session/token

### ISSUE THREAD

**Issue by samshuai** [Jewel591/xssmap#1]
需要测试内部系统，需要登陆，并且现在很少有没有验证码的系统了

**Comment by Jewel591** [comment]
目前还不支持配置 cookie，后续会规划添加上滴。

**Comment by Jewel591** [comment]
> 需要测试内部系统，需要登陆，并且现在很少有没有验证码的系统了
新版本已经支持 cookie
